name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
      - name: 'Node setup (v16)'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install project dependencies
        run: yarn --immutable
      - name: 'Build'
        run: yarn run build